services:
  postgres:
    image: postgres:latest
    container_name: postgres_books
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: books
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   postgres_data:
